# Generated by Django 4.1.7 on 2023-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='img',
            field=models.ImageField(default=1, upload_to='departments'),
            preserve_default=False,
        ),
    ]
