# Generated by Django 4.1.7 on 2023-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_name',
            new_name='dept_name',
        ),
    ]
