# Generated by Django 4.1.7 on 2023-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
